language: java
jdk:
        - oraclejdk8

env:
        # Source directory for the project
        - SRCDIR=PL2

script: cd $SRCDIR && mvn verify

# use newer version of java
addons:
  apt:
    packages:
      - oracle-java8-installer

